services:
  postgres:
    container_name: fraud_detection_db
    image: postgres:17  # Use a stable version
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_detection_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "fraud_detection_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_mlflow_app
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MLFLOW_TRACKING_URI=postgresql://admin:password@fraud_detection_db:5432/mlflow
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: fraud-detection_postgres_data

